config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  get 'notifications/show'

  get 'notifications/new'

  resources :users

  resources :stocks
    get "signin" => "users#signin"

  get "search" => "users#search"

  root 'welcome#index'
  get "welcome/about" => "welcome#about"
  get "stocks/stock/text/id=:id" => "stocks#text"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock

end

app/models/stock.rb
require "market_beat"
class Stock < ActiveRecord::Base
  belongs_to :user

    def self.price(ticker)
        result = MarketBeat.last_trade_real_time(ticker)
        return result
    end

    def self.lookup(company)
        url = "http://d.yimg.com/autoc.finance.yahoo.com/autoc?query=#{company}&callback=YAHOO.Finance.SymbolSuggest.ssCallback"
        response = Net::HTTP.get_response(URI.parse(url))
        response.body[39..-2]
    end

    def self.text(stock)
        stock = Stock.where(:id => stock).first
        user_id = stock.user_id
        user = User.where(:id => user_id).first
        phone = user.phone
        account_sid = "AC35d0abacd00f2ffcc065ca1d53c8b930"
        auth = "0b1863df59c77930f6d4a12352be5679"
        begin
            client = Twilio::REST::Client.new(account_sid, auth)
            response = client.account.messages.create( {
                :body => "This is your test Stock Tracking email",
                :to => phone,
                :from => "+19147757419",
            })

            puts response.body
        rescue Twilio::REST::RequestError => e
            puts e.message
            return false
        end
        return true
    end


end

app/models/user.rb
class User < ActiveRecord::Base
    validates :email, uniqueness: true
    validates :phone, uniqueness: true
    validates :email, presence: true
    validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)
    puts "COMPANY ----< #{params[:company]}"
    json = Stock.lookup(@stock.company)
    json = JSON.parse(json)
    json = json["ResultSet"]["Result"][0]
    @stock.ticker = json["symbol"]
    @stock.company = json["name"]
    @stock.price = Stock.price(json["symbol"])

    if @stock.save
      redirect_to stock_path(@stock.id)
    else
      redirect_to root_path
    end
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def index
  end

  def destroy
    stock = Stock.find(params[:id])
    stock.destroy
    redirect_to :back
  end

  def text
    if Stock.text(params[:id])
      redirect_to :back
    else
      redirect_to root_path
    end
  end

private

    def stock_params
        params.require(:stock).permit(:company, :owned, :watching, :ticker, :price, :user_id)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @stock = Stock.where(user_id: params[:id])
  end

  def new
    @user = User.new
  end

def signin
  end

  def search
    user = User.where(email: params[:email]).first
    if user.nil?
      redirect_to root_path
    end
    redirect_to user_path(user.id)
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to user_path(@user.id)
    else
        redirect_to root_path
    end
end

private

def user_params
    params.require(:user).permit(:email, :phone)
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StockTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="nav_bar">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", welcome_about_path %></li>
</ul>

<div class="content">
<%= yield %>
</div>
<img alt="wallstreet" src="http://upload.wikimedia.org/wikipedia/commons/e/ea/NY_stock_exchange_traders_floor_LC-U9-10548-6.jpg" style="z-index: -1">
</body>
</html>

app/views/notifications/index.html.erb
<h1>Notifications#index</h1>
<p>Find me in app/views/notifications/index.html.erb</p>

app/views/notifications/new.html.erb
<h1>Notifications#new</h1>
<p>Find me in app/views/notifications/new.html.erb</p>

app/views/notifications/show.html.erb
<h1>Notifications#show</h1>
<p>Find me in app/views/notifications/show.html.erb</p>

app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<p>Find me in app/views/stocks/index.html.erb</p>

app/views/stocks/new.html.erb
<div class="form" style="width:75%; padding:20px">
    <%= form_for @stock do |s|%>
    <p>Company    <%= s.text_field :company %></p>

    <p>Do you <strong>own</strong><%= s.check_box :owned %> this stock? Or just want to <strong>keep an eye on it</strong><%= s.check_box :watching %></p>
    <%= s.hidden_field :user_id, :value => params[:id] %>

    <%= s.fields_for :notifications do |n| %>
    <h4 style="font-size:22px">How would you like to be notified?</h4>
    <p>When the stock goes <%= n.check_box :above%> above
    <%= n.number_field :high %> and/or when the stock goes
    <%= n.check_box :below%> below <%= n.number_field :low%></p>
    <% end %>
        <%= s.submit "Submit", class: "submit" %>

    <% end %>
</p>

app/views/stocks/show.html.erb
<h2>Listing for <%= @stock.company %> </h2>
<p><%= link_to "Back to my Account", user_path(@stock.user_id) %></p>
<h4>Track the <%= @stock.ticker%> ticker</h4>
<p>Opening price: <%= @stock.price%></p>
<p>Send a <%= link_to 'test notification', "stock/text/id=#{@stock.id}"%></p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h2>Create a new account</h2>

<div class="form">

    <%= form_for @user do |u| %>
    <div class="inputs">
        <p>Email<%= u.text_field :email %></p>
        <p>Phone<%= u.text_field :phone %></p>
    <%= u.submit 'Create Account', class: "submit"%>
    </div>

    <% end %>
</div>

app/views/users/show.html.erb
<h2>Welcome <%= @user.email %></h2>
<%= link_to "Follow a new stock", new_stock_path(:id => @user.id), class: "new_stock" %>

<hr>
<% if !(@stock.count <= 0) %>
<h4>Stocks You're Interested In</h4>

    <table>
    <tr>
    <th>Company</th><th>Ticker</th><th>Price</th><th>Status</th><th>Destroy</th>
    </tr>
    <% @stock.each do |s| %>
        <tr>
        <td><%= link_to s.company, stock_path(s.id) %></td>
        <td><%= s.ticker %></td>
        <td><%= s.price %></td>
        <td><%= s.owned ? "owned" : (s.watching ? "watching" : "none") %></td>
        <td><%= link_to "Delete", s, method: :delete %></td>
        </tr>
    <% end %>
    </table>
<% end %>

app/views/users/signin.html.erb
<h2 class="new_accnt">Sign-In Below to See Your Stocks</h2>


<div class="form">

    <%= form_tag("/search", method: "get") do %>

    <div class="inputs">
        <%= label_tag(:email) %> <br>
        <%= text_field_tag(:email) %>

        <%= submit_tag("Submit", class: "submit") %>
    </div>

    <% end %>
</div>

app/views/welcome/about.html.erb
<h3>About Stock Tracker</h3>

<hr>

<p>Stock tracker lets you track your favorite stocks for highs and lows. You've done the research and you know what you're stocks are worth so there's no need to track them closely. However if prices surge maybe they've reached a roof you've set, or maybe they're undervalued and you should buy more. Stock tracker will help keep you informed on the prices of your assets so you can capitalize on the research you've done.</p>

app/views/welcome/index.html.erb
<h2>Welcome To Stock Trader</h2>
<p>Follow <%= link_to "this", new_user_path, :class => "link" %> link to make a new account.</p>
    <p>And <%= link_to "this", signin_path, class: "link" %> link to sign-in</p>